version: "3.9"

services:

  db:
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "${DB_NAME:-wallet_db}"
      MYSQL_USER: "${DB_USER:-wallet_db_user}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"

  wallet_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: "${DB_HOST:-db}"
      DB_PORT: "${DB_PORT:-3307}"
      DB_NAME: "${DB_NAME:-wallet_db}"
      DB_USER: "${DB_USER:-wallet_db_user}"
      DB_PASSWORD: "${DB_PASSWORD:-secret}"
      DEBUG: "${DEBUG:-True}"
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
