# Generated by Django 5.1 on 2024-09-03 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Label"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=18, max_digits=30, verbose_name="Balance"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "txid",
                    models.CharField(max_length=255, unique=True, verbose_name="TxID"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=18, max_digits=30, verbose_name="Amount"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="api.wallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
